export const JWT_CLAIMS = {
  ID: 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier',
  EMAIL: 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress',
  NAME: 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name',
  PHONE_NUMBER: 'phone_number',
  NICKNAME: 'nickname',
  EMAIL_VERIFIED: 'email_verified',
  PHONE_VERIFIED: 'phone_verified',
  DOCUMENT_VERIFICATION_STATUS: 'document_verification_status',
  ROLE: 'http://schemas.microsoft.com/ws/2008/06/identity/claims/role'
} as const;

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/api/auth/login',
    REGISTER: '/api/auth/register',
    REFRESH: '/api/auth/refresh',
    REQUEST_EMAIL_VERIFICATION: '/api/auth/email-verification/request',
    CONFIRM_EMAIL_VERIFICATION: '/api/auth/email-verification/confirm',
    REQUEST_PHONE_VERIFICATION: '/api/auth/phone-verification/request',
    CONFIRM_PHONE_VERIFICATION: '/api/auth/phone-verification/confirm',
    UPLOAD_DOCUMENT_VERIFICATION_FILES: '/api/auth/document-verification/upload',
    CREATE_DOCUMENT_VERIFICATION: '/api/auth/document-verification/request',
    MY_DOCUMENT_VERIFICATIONS: '/api/auth/document-verification/my',
    PUBLIC_PROFILE: (userId: string) => `/api/auth/users/${userId}/public-profile`,
  },
  LOTS: {
    LIST: '/api/lots',
    DETAIL: (id: string) => `/api/lots/${id}`,
    BIDS: (id: string) => `/api/lots/${id}/bids`,
    IMAGES: (id: string) => `/api/lots/${id}/images`,
    CREATE: '/api/lots',
    UPDATE: (id: string) => `/api/lots/${id}`,
    SUBMIT_FOR_MODERATION: (id: string) => `/api/lots/${id}/submit-for-moderation`,
    APPROVE: (id: string) => `/api/lots/${id}/approve`,
    REJECT: (id: string) => `/api/lots/${id}/reject`,
    UNFREEZE: (id: string) => `/api/lots/${id}/unfreeze`,
    RESOLVE_DISPUTE: (id: string) => `/api/lots/${id}/resolve-dispute`,
    REVIEWS: (id: string) => `/api/lots/${id}/reviews`,
  },
  SELLERS: {
    REVIEWS: (sellerId: string) => `/api/sellers/${sellerId}/reviews`,
    TRUST: (sellerId: string) => `/api/sellers/${sellerId}/trust`,
  },
  BIDS: {
    MY: '/api/bids/my',
  },
  PAYMENT: {
    BALANCE: '/api/payment/balance',
    TRANSACTIONS: '/api/payment/transactions',
    TOPUP: '/api/payment/topup',
    TOPUP_CHECKOUT: '/api/payment/topup/checkout',
  },
  NOTIFICATIONS: {
    LIST: '/api/notifications',
    UNREAD_COUNT: '/api/notifications/unread-count',
    MARK_READ: (id: string) => `/api/notifications/${id}/read`,
  },
  ADMIN: {
    PENDING_LOTS: '/api/admin/lots/pending',
    FROZEN_LOTS: '/api/admin/lots/frozen',
    DISPUTES: '/api/admin/disputes',
    BANNED_USERS: '/api/admin/users/banned',
    BAN: (userId: string) => `/api/admin/users/${userId}/ban`,
    UNBAN: (userId: string) => `/api/admin/users/${userId}/unban`,
    DOCUMENT_VERIFICATION_PENDING: '/api/auth/document-verification/pending',
    DOCUMENT_VERIFICATION_APPROVE: (id: string) => `/api/auth/document-verification/${id}/approve`,
    DOCUMENT_VERIFICATION_REJECT: (id: string) => `/api/auth/document-verification/${id}/reject`,
    DOCUMENT_VERIFICATION_FILE: (id: string, fileType: 'passport' | 'selfie') => `/api/auth/document-verification/${id}/files/${fileType}`,
  },
  IMAGES: {
    UPLOAD: (lotId: string) => `/api/lots/${lotId}/images`,
    DELETE: (lotId: string, imageId: string) => `/api/lots/${lotId}/images/${imageId}`,
  },
} as const;
